website/__init__.py
from flask import Flask


def create_app():
    app = Flask(__name__, static_folder="static")
    app.config["SECRET_KEY"] = "27493hd9fh03h9u4bv830tj9493jld02n4fy7.874nvocn393nuvy34f6cnHGDn8Bfinf"

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    return app

website/auth.py
from flask import Blueprint


auth = Blueprint("auth", __name__)

@auth.route("/login")
def login():
    return "<h2>login<h2>"


@auth.route("/logout")
def logout():
    return "<h2>logout<h2>"


@auth.route("/sign-up")
def sign_up():
    return "<h2>Sign Up<h2>"

website/views.py
from flask import Blueprint, render_template, request

from website.static._python.cases_scripts import to_sentence_case, to_title_case, to_capitalize_case

views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST", "PUT"])
def home():
    if request.method == "PUT":
        initial_text = request.form.get("initial_text")
        char_count = len(initial_text)
        if request.form.get("submit_upper") == "uppercase":
            initial_text = initial_text.upper()
        elif request.form.get("submit_lower") == "lowercase":
            initial_text = initial_text.lower()
        elif request.form.get("submit_capitalize") == "capitalize":
            initial_text = to_capitalize_case(initial_text)
        elif request.form.get("submit_title") == "title":
            initial_text = to_title_case(initial_text)
        elif request.form.get("submit_sentence") == "sentence":
            initial_text = to_sentence_case(initial_text)
        return render_template("_partials/text_response.html", initial_text=initial_text, char_count=char_count)
    return render_template("home.html")

website/templates/_partials/text_response.html
<form method="PUT" id="text_form">
  <label for="initial_text" class="form-label mt-4"></label>
  <div class="textarea-container">
    <textarea
      class="form-control user-text"
      name="initial_text"
      id="initial_text"
      placeholder="Type your text here.."
      rows="15"
      onkeyup="countChar(this)"
    >{{ initial_text }}</textarea>
    <button type="button" id="clearButton" class="delete">
      <span class="material-symbols-outlined">close</span>
    </button>
    <button id="copyButton" type="button" class="copy">
      <span id="copyIcon" class="material-symbols-outlined">content_copy</span>
    </button>
  </div>
  <br />
  <div>
    <button
      type="submit"
      name="submit_upper"
      value="uppercase"
      class="btn btn-secondary"
      hx-put="{{ url_for('views.home') }}"
    >
      Upper Case
    </button>
    <button
      type="submit"
      name="submit_lower"
      value="lowercase"
      class="btn btn-secondary"
      hx-put="{{ url_for('views.home') }}"
    >
      Lower Case
    </button>
    <button
      type="submit"
      name="submit_capitalize"
      value="capitalize"
      class="btn btn-secondary"
      hx-put="{{ url_for('views.home') }}"
    >
      Capitalize Case
    </button>
    <button
      type="submit"
      name="submit_title"
      value="title"
      class="btn btn-secondary"
      hx-put="{{ url_for('views.home') }}"
    >
      Title Case
    </button>
    <button
    type="submit"
    name="submit_sentence"
    value="sentence"
    class="btn btn-secondary"
    hx-put="{{ url_for('views.home') }}"
    >
      Sentence Case
    </button>
  </div>
</form>
<script src="static/_js/copy_clear_button.js" defer></script>

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/svg+xml" href="{{ url_for('static', filename='images/logo/logo.svg') }}"/>
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/logo/logo.png') }}"/>
    <link rel="icon" type="image/jpg" href="{{ url_for('static', filename='images/logo/logo.jpg') }}"/>
    {% block description %}{% endblock %}
    <link href="https://caseconvertonline.org/" rel="canonical" />
    <link
      href="{{ url_for('static', filename='bs/css/bootstrap.css') }}"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='bs/css/custom.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />
    <link
      href="https://{{cdn}}/prismjs@v1.x/themes/prism.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script
      src="https://unpkg.com/htmx.org@2.0.2"
      integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ"
      crossorigin="anonymous"
    ></script>
    <script type="application/ld+json">
        {"@context":"https://schema.org","@type":"Project","name":"Convert Case","url":"https://caseconvertonline.org/","sameAs":["https://caseconvertonline.org/"]}
    </script>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-RS4BQ54DL7"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-RS4BQ54DL7');
    </script>
    <script src="static/_js/theme.js" defer></script>
    <script src="static/_js/copy_clear_button.js" defer></script>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg fixed-top bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('views.home') }}"
            ><img src="https://www.caseconvertonline.org/static/images/logo/logo-caseconvertonline.svg" alt="CaseConvertOnline" width="160" height="50"></a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarResponsive"
            aria-controls="navbarResponsive"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav me-auto">
            </ul>
            <ul class="navbar-nav ms-md-auto">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle d-flex align-items-center"
                  href="#"
                  id="theme-menu"
                  aria-expanded="false"
                  data-bs-toggle="dropdown"
                  data-bs-display="static"
                  aria-label="Toggle theme"
                >
                  <i class="bi bi-circle-half"></i>
                  <span class="d-lg-none ms-2">Toggle theme</span>
                </a>
                <ul
                  class="dropdown-menu dropdown-menu-end"
                  data-bs-propper="static"
                >
                  <li>
                    <button
                      type="button"
                      class="dropdown-item d-flex align-items-center"
                      data-bs-theme-value="light"
                      aria-pressed="false"
                    >
                      <i class="bi bi-sun-fill"></i
                      ><span class="ms-2">Light</span>
                    </button>
                  </li>
                  <li>
                    <button
                      type="button"
                      class="dropdown-item d-flex align-items-center"
                      data-bs-theme-value="dark"
                      aria-pressed="true"
                    >
                      <i class="bi bi-moon-stars-fill"></i
                      ><span class="ms-2">Dark</span>
                    </button>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="bs-docs-section">
        {% block content %} {% endblock %}
      </div>
    </div>
    <footer id="footer">
      <div class="footer-container">
        <div class="footer-column">
          <h3>Contact Us</h3>
          <ul>
              <li>Email: team@caseconvertonline.org</li>
          </ul>
          <div class="social-icons">
            <a href="//www.dmca.com/Protection/Status.aspx?ID=f6165f17-1a55-489a-bc83-7ad70940e321" title="DMCA.com Protection Status" class="dmca-badge" target="_blank" rel="noopener noreferrer">
              <img src ="https://images.dmca.com/Badges/dmca_protected_sml_120q.png?ID=f6165f17-1a55-489a-bc83-7ad70940e321"  alt="DMCA.com Protection Status" /></a>
            <script src="https://images.dmca.com/Badges/DMCABadgeHelper.min.js"></script>
          </div>
        </div>
        <div class="footer-column">
          <h3>Made By</h3>
          <div class="social-icons">
              <a href="https://www.linkedin.com/in/mykhailo-pyrkh-691000261/" class="social-icon" target="_blank" rel="noopener noreferrer"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
              </svg></a>
          </div>
      </div>
      </div>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %}Convert Case Online | Easily Change Uppercase to Lowercase and more!{% endblock %}
{% block description %}<meta name="description" content="Case Converter Tool 2024 – Transform text to uppercase, lowercase, title case, sentence case, capitalize case  in one click with our free online converter">{% endblock %}
{% block content%}
<div class="page-header" id="banner">
  <div class="row">
    <h1>Online Case Converter</h1>
  </div>
  <div>
      <p>
        Transform Your Text in 1 Seconds: Get Perfect Case Conversion Now!
      </p>
  </div>
</div>
<form class="form-label mt-4" method="PUT" id="text_form" hx-target="this" hx-swap="outrHTML">
  <label for="initial_text" class="form-label mt-4"></label>
  <div class="textarea-container">
    <textarea
      class="form-control user-text"
      name="initial_text"
      id="initial_text"
      placeholder="Type your text here.."
      rows="15"
      onkeyup="countChar(this)"
    ></textarea>
    <button type="button" id="clearButton" class="delete">
      <span class="material-symbols-outlined">close</span>
    </button>
    <button id="copyButton" type="button" class="copy">
      <span id="copyIcon" class="material-symbols-outlined">content_copy</span>
    </button>
  </div>
  <br />
  <div>
    <button
      type="submit"
      name="submit_upper"
      value="uppercase"
      class="btn btn-secondary"
      hx-put="{{ url_for('views.home') }}"
    >
      Upper Case
    </button>
    <button
      type="submit"
      name="submit_lower"
      value="lowercase"
      class="btn btn-secondary"
      hx-put="{{ url_for('views.home') }}"
    >
      Lower Case
    </button>
    <button
      type="submit"
      name="submit_capitalize"
      value="capitalize"
      class="btn btn-secondary"
      hx-put="{{ url_for('views.home') }}"
    >
      Capitalize Case
    </button>
    <button
      type="submit"
      name="submit_title"
      value="title"
      class="btn btn-secondary"
      hx-put="{{ url_for('views.home') }}"
    >
      Title Case
    </button>
    <button
      type="submit"
      name="submit_sentence"
      value="sentence"
      class="btn btn-secondary"
      hx-put="{{ url_for('views.home') }}"
    >
      Sentence Case
    </button>
  </div>
</form>
<div class="bs-docs-section">
  <small>Numbers of characters: </small>
  <span id="charNum">0</span>
</div>
<div class="bs-docs-section">
  <div class="card-mb-3">
    <div class="card">
      <div class="card-body">
        <h2 class="card-title">Welcome to Case Converter Tool</h2>
        <p class="card-text">A simple and convenient tool for instant text case conversion — that's Case Convert. Format text online by switching between uppercase, lowercase, title case, and other case formats with one click. Edit your text according to commonly accepted writing and style rules. Get immediate and accurate results for professional, academic, or personal use.</p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h2 class="card-title">How to Convert Case Online?</h2>
        <p class="card-text">Our online tool is your personal assistant for converting text between different cases in just seconds. It's intuitive, quick, and, more importantly, correct. With Convert Case, you can always be assured of accurate results. Based on innovative algorithms, it efficiently formats texts of any length for future reference. Convert the case in three easy steps:</p>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Enter the text.</strong> Type your text or simply paste it into the input box.</li>
          <li class="list-group-item"><strong>Choose the case style.</strong> Select the desired case format and click on it to start the conversion.</li>
          <li class="list-group-item"><strong>Done! Get your results.</strong> Copy the edited text manually or simply click the 'Copy to Clipboard' button.</li>
        </ul>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h2 class="card-title">Case Convert Options</h2>
        <p class="card-text">The Convert Case online tool is designed for the most commonly used case styles:</p>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Upper Case</li>
          <li class="list-group-item">Lower Case</li>
          <li class="list-group-item">Capitalize Case</li>
          <li class="list-group-item">Title Case</li>
          <li class="list-group-item">Sentence Case</li>
        </ul>
        <p class="card-text">Whether you need to fix formatting mistakes, check your work, or simply edit the text in accordance with spelling rules, use the converter to save time and always get flawless results.</p>
      </div>
    </div>
  </div>
</div>
<div class="bs-docs-section">
  <div class="row">
    <div class="col-lg-4">
      <div class="bs-component">
        <div class="card border-light mb-3" style="max-width: 20rem;">
          <div class="card-body">
            <h3 class="card-title">Upper Case</h3>
            <p class="card-text">Forget about the time-consuming task of retyping acronyms manually, where it's easy to miss a letter or even several. Automatically highlight individual words or phrases for titles or to emphasize key parts of the text. Edit your text stress-free and time-efficiently, following business documentation guidelines or your personal preferences.</p>
            <p><strong>Example: </strong> EMBRACE CHANGE WITH COURAGE</p>
          </div>
        </div>
        <div class="card border-light mb-3" style="max-width: 20rem;">
          <div class="card-body">
            <h3 class="card-title">Capitalize Case</h3>
            <p class="card-text">Some styles require a special layout for headings, names, or titles where every word begins with a capital letter. If articles, conjunctions, and prepositions in your text were previously lowercase, you can now fix them effortlessly. Tidy up your text with our Convert Case tool for the best formatting results.</p>
            <p><strong>Example:</strong> Embrace Change With Courage</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="bs-component">
        <div class="card border-light mb-3" style="max-width: 20rem;">
          <div class="card-body">
            <h3 class="card-title">Sentence Case</h3>
            <p class="card-text">No matter what case style your text is in, you can automatically correct sentences by capitalizing the first words and proper nouns. Paste phrases or long texts, activate the sentence case conversion feature, copy the results, and continue working with your documents. Case Convert online is an indispensable tool for preparing flawless texts.</p>
            <p><strong>Example:</strong> Embrace change with courage</p>
          </div>
        </div>
        <div class="card border-light mb-3" style="max-width: 20rem;">
          <div class="card-body">
            <h3 class="card-title">Title Case</h3>
            <p class="card-text">Sometimes, it can be difficult to figure out the correct spelling, especially when it comes to headlines. Even a professional can easily make mistakes. Simply type manually or input your text, and our tool will correct it. You don't need to know all the rules to make your text error-free.</p>
            <p><strong>Example:</strong> Embrace Change with Courage</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="bs-component">
        <div class="card border-light mb-3" style="max-width: 20rem;">
          <div class="card-body">
            <h3 class="card-title">Lower Case</h3>
            <p class="card-text">Did you find a mistake, or just need a quick formatting fix? Our online converter will handle it. The lowercase conversion feature is easily activated by pressing the 'Lower Case' button, and your text is ready to use in an instant. Pressed Caps Lock is no longer a problem.</p>
            <p><strong>Example:</strong> embrace change with courage</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}